name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: SebRollen/toml-action@v1.2.0
        id: toml_version
        with:
          file: 'pyproject.toml'
          field: 'project.version'
      - uses: SebRollen/toml-action@v1.2.0
        id: toml_package_name
        with:
          file: 'pyproject.toml'
          field: 'tool.elin.package-name'

      - run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'poetry'

      - run: poetry install
      - run: poetry run invoke dist

      - uses: actions/upload-artifact@v4
        with:
          name: '${{steps.toml_package_name.outputs.value}}-v${{steps.toml_version.outputs.value}}.zip'
          path: 'dist/${{steps.toml_package_name.outputs.value}}-v${{steps.toml_version.outputs.value}}.zip'

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: 'dist/${{steps.toml_package_name.outputs.value}}-v${{steps.toml_version.outputs.value}}.zip'
